# -*- coding: utf-8 -*-
"""MGSC410HW4PT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tfor6VoxfmfdBO1oru2KsZiclUCkbqGg
"""

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import random
from plotnine import *
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler #Z-score variables
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split # simple TT split cv
from sklearn.model_selection import KFold # k-fold cv
from sklearn.model_selection import LeaveOneOut #LOO cv
from sklearn.model_selection import cross_val_score # cross validation metrics
from sklearn.model_selection import cross_val_predict # cross validation metrics
from sklearn.preprocessing import LabelBinarizer


from sklearn.linear_model import LinearRegression # Linear Regression Model
from sklearn.preprocessing import StandardScaler #Z-score variables
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score #model evaluation

from sklearn.model_selection import train_test_split # simple TT split cv
from sklearn.model_selection import KFold # k-fold cv
from sklearn.model_selection import LeaveOneOut #LOO cv
from sklearn.model_selection import cross_val_score # cross validation metrics
from sklearn.model_selection import cross_val_predict # cross validation metrics

import matplotlib.pyplot as plt
import numpy as np
SalesData = pd.read_csv("https://raw.githubusercontent.com/sreyavadlamudi/MGSC410/main/SALESgraph.csv?token=GHSAT0AAAAAACBS7WLYQXTA24GG42YTUKECZB7PVAQ")
SalesData = SalesData.dropna()
SalesData = SalesData.reset_index()
SalesData

SalesData = SalesData.sort_values(by='Weekly_Sales', ascending=False)
print(ggplot(SalesData, aes(x="Store", y="Weekly_Sales", fill = "Store")) + geom_col() + ggtitle("Weekly_Sales vs Stores"))
#take average weekly sales for each store and plot

SalesData = SalesData.sort_values(by=['Weekly_Sales'], ascending=False)

# Print out top 10 stores with highest weekly sales
print(SalesData.head(10))



#Weighted Averages after combined:
 #are in excel
# also wanna put stores in these big areas
#OVERALL:
#Weighted Temperature: 68.06682396
#Weighted Fuel Price: 3149.258183
#Weighted CPI: 1966203417
#Weighted Unemployment: 7613.774365
#Weighted IsHoliday: 0